version: '3.1'
services: 
  mongohost:
    image: mongo:7
    restart: always
    container_name: mongodb
    volumes: 
      - mongo:/data/db
    ports:
    - 27017:27017

  restapi:
    build: .
    restart: always
    container_name: restapi
    ports:
     - 5000:5231
    depends_on:
      - mongohost

volumes:
  mongo: