pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                script {
                    // Checkout the code from the Git repository
                    checkout scm
                }
            }
        }

        stage('Build and Test') {
            steps {
                script {
                    // Build the NUnit testing project and run tests
                    dir('NUnitTesting') {
                        sh 'dotnet test'
                    }
                }
            }
        }
    }

   
   post {
        always {
            // Archive the NUnit test results
            nunit testResultsPattern: 'NUnitTesting/**/TestResult.xml'
        }
    }
}